### ISSUE TITLE
Change strategy to create PRs in downstream repos

### ISSUE THREAD

**Issue by rgildein** [canonical/solutions-engineering-automation#111]
Part of our initiative of improving central file management is to improve our process in this automatization. The idea is that instead of create PRs in downstream repos after PR in this repo is created, we should create PRs straight forwards.

So instead, the workflow will change the following way:
- Create Draft PR -> CI trigger and user can see the output, without PRs in downstream being created
- convert Draft to regular PR -> PRs in downstream will be created
- reviewer check also PRs in downstream and approve only if workflows do not crash due to some type etc.
- [optional] After PR in this repo is closed, another CI could enable auto-merge in downstream repos and provide approval from the bot. If CI passes, the downstream repos will be merged automatically.

Prerequisite is that all downstream PRs are linked with original repo (the original PR is mention in the downstream, so GitHub would do rest).

related: #52

**Comment by rgildein** [comment]
It was fixed by #112, however for now no auto-merge.

**Comment by Pjack** [comment]
Reopening this issue as the changes in #119 were reverted. We will allocate dedicated time to address it later in this cycle.

**Comment by samuelallan72** [comment]
I like this general flow, but I think we should only be merging PRs generated from main. I think we can do this using the same flow with some care and being sure that it's very clear on the automated PRs which ones are ready for merge or not. Remember with this flow we'll potentially have multiple PRs open to each target repository if we have multiple PRs to automation, and they may or may not conflict.

**Comment by samuelallan72** [comment]
Note that I do strongly see the downsides of only having the downstream PRs created after merging to main here (I've been bitten by merging something with a simple issue, then immediately needing a follow up PR that could have been avoided...). I just think we need to take care to develop a polished alternative to avoid introducing new problems. :sweat_smile:
