### ISSUE TITLE
Add centrally managed TICS workflows

### ISSUE THREAD

**Issue by Deezzir** [canonical/solutions-engineering-automation#115]
Projects:
- `smarctl-exporter-snap` - https://github.com/canonical/smartctl-exporter-snap/pull/18
- `dcgm-exporter-snap` - https://github.com/canonical/dcgm-snap/pull/46
- `charmed-openstack-exporter-snap` - https://github.com/canonical/charmed-openstack-exporter-snap/pull/13

**Comment by samuelallan72** [comment]
@Deezzir the linked PRs have been merged. Are there any blockers to moving these TICS workflows to automation now? :)

**Comment by Deezzir** [comment]
Feel free to take the item, if you want, you guys have more experience with the central management :)
