### ISSUE TITLE
Automated PRs should be updated if possible

### ISSUE THREAD

**Issue by samuelallan72** [canonical/solutions-engineering-automation#63]
Currently, the workflow to apply changes simply opens new PRs with the changes, even if there are already open pending PRs to target repositories.  It would be better if it detecting that a PR was already open, and updated that PR instead of creating a new one.

**Comment by samuelallan72** [comment]
Note: a fix might be simple - use a consistent hardcoded branch name for PRs.

**Comment by chanchiwai-ray** [comment]
> Note: a fix might be simple - use a consistent hardcoded branch name for PRs.

we can test with a test repo using PAT + terraform + some PRs
